name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-desktop:
    name: Build Test (${{ matrix.os.prettyname }})
    runs-on: ${{ matrix.os.fullname }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { prettyname: Windows, fullname: windows-latest }
          - { prettyname: Linux, fullname: ubuntu-latest }
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Packages
        run: dotnet restore osu.Desktop.slnf

      - name: Compile Desktop Solution
        run: dotnet build -c Debug osu.Desktop.slnf
